from core.analyzer import Analyzer


class ConsensusAgent:
    def __init__(self):
        self.analyzer = Analyzer()

    def generate_consensus(self, ratings: list[dict], bull_bear_points: list[dict]) -> dict:
        consensus = self.analyzer.consensus_analysis(ratings)
        sentiment = self.analyzer.sentiment_score(bull_bear_points)
        themes = self.analyzer.bull_bear_themes(bull_bear_points)
        broker_comp = self.analyzer.broker_comparison(ratings)
        trends = self.analyzer.trend_analysis(ratings)

        upside = 0
        high_target = consensus.get("high_target_price", 0)
        if high_target > 0:
            upside = round(
                (consensus["avg_target_price"] - high_target * 0.85) / (high_target * 0.85) * 100,
                1
            )

        return {
            "consensus_rating": self._determine_consensus_rating(
                consensus.get("rating_distribution", {})
            ),
            "target_price": consensus,
            "sentiment": sentiment,
            "themes": themes,
            "broker_comparison": broker_comp,
            "trends": trends,
            "upside_potential": upside,
        }

    def generate_report(self, ticker: str, company: str, consensus: dict, reports: list[dict]) -> str:
        lines = []
        lines.append(f"# AI Investment Research Report: {company} ({ticker})")
        lines.append("")
        lines.append("## 1. Executive Summary")
        lines.append(
            f"Based on analysis of {consensus['target_price']['total_reports']} broker reports, "
            f"the consensus rating is **{consensus['consensus_rating']}** "
            f"with an average target price of **{consensus['target_price']['avg_target_price']:,.0f}**. "
            f"Bullish sentiment stands at {consensus['sentiment']['bullish']}%."
        )
        lines.append("")
        lines.append("## 2. Company Overview")
        lines.append(f"{company} ({ticker}) is covered by {len(consensus['broker_comparison'])} brokers.")
        lines.append("")
        lines.append("## 3. Broker Comparison")
        lines.append("| Broker | Rating | Target Price |")
        lines.append("|--------|--------|-------------|")
        for b in consensus["broker_comparison"]:
            tp = f"{b['target_price']:,.0f}" if b['target_price'] else "N/A"
            lines.append(f"| {b['broker']} | {b['rating']} | {tp} |")
        lines.append("")
        lines.append("## 4. Bull Thesis")
        for theme, count in consensus["themes"]["bull_themes"].items():
            lines.append(f"- **{theme}**: mentioned {count} times")
        lines.append("")
        lines.append("## 5. Bear Thesis")
        for theme, count in consensus["themes"]["bear_themes"].items():
            lines.append(f"- **{theme}**: mentioned {count} times")
        lines.append("")
        lines.append("## 6. Financial Outlook")
        lines.append(f"Average target price: {consensus['target_price']['avg_target_price']:,.0f}")
        lines.append(f"Target range: {consensus['target_price']['low_target_price']:,.0f} - {consensus['target_price']['high_target_price']:,.0f}")
        lines.append("")
        lines.append("## 7. Target Price Analysis")
        lines.append(f"- High: {consensus['target_price']['high_target_price']:,.0f}")
        lines.append(f"- Median: {consensus['target_price']['median_target_price']:,.0f}")
        lines.append(f"- Low: {consensus['target_price']['low_target_price']:,.0f}")
        lines.append(f"- Upside: {consensus['upside_potential']}%")
        lines.append("")
        lines.append("## 8. Trend Analysis")
        lines.append(f"- Upgrades: {consensus['trends']['upgrades']}")
        lines.append(f"- Downgrades: {consensus['trends']['downgrades']}")
        lines.append("")
        lines.append("## 9. Market Sentiment")
        lines.append(f"- Bullish: {consensus['sentiment']['bullish']}%")
        lines.append(f"- Neutral: {consensus['sentiment']['neutral']}%")
        lines.append(f"- Bearish: {consensus['sentiment']['bearish']}%")
        lines.append("")
        lines.append("## 10. AI Investment Conclusion")
        if consensus['sentiment']['bullish'] > 60:
            lines.append("The overall market sentiment is strongly bullish.")
        elif consensus['sentiment']['bullish'] > 40:
            lines.append("The market sentiment is moderately positive.")
        else:
            lines.append("The market sentiment is cautious.")
        lines.append("")
        lines.append("---")
        lines.append(f"*Generated by Investment Research Intelligence Platform*")
        return "\n".join(lines)

    def _determine_consensus_rating(self, distribution: dict) -> str:
        if not distribution:
            return "N/A"
        total = sum(distribution.values())
        if total == 0:
            return "N/A"
        buy_pct = distribution.get("BUY", 0) / total * 100
        if buy_pct >= 60:
            return "BUY"
        elif buy_pct >= 30:
            return "HOLD"
        else:
            return "SELL"
